server:
  port: "${SERVER_PORT}"
spring:
  application:
    name: "${SPRING_APPLICATION_NAME}"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: "${H2_CONSOLE_ENABLED}"
      path: "${H2_CONSOLE_PATH}"
  profiles:
    active: "${PROFILE_ACTIVE}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  api-docs:
    path: "/v3/api-docs"
    enabled: true
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true
    try-it-out-enabled: true
  show-actuator: false